[2023-01-04T13:39:03.457+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.MS1_Data_Cleaning_and_Transformation scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-04T13:39:03.466+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.MS1_Data_Cleaning_and_Transformation scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-04T13:39:03.467+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T13:39:03.467+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T13:39:03.564+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T13:39:03.586+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): MS1_Data_Cleaning_and_Transformation> on 2023-01-02 00:00:00+00:00
[2023-01-04T13:39:03.591+0000] {standard_task_runner.py:55} INFO - Started process 225 to run task
[2023-01-04T13:39:03.595+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'MS1_Data_Cleaning_and_Transformation', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmpp3lx34m_']
[2023-01-04T13:39:03.596+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask MS1_Data_Cleaning_and_Transformation
[2023-01-04T13:39:03.658+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.MS1_Data_Cleaning_and_Transformation scheduled__2023-01-02T00:00:00+00:00 [running]> on host 980a01aa00ba
[2023-01-04T13:39:03.728+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=MS1_Data_Cleaning_and_Transformation
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-04T13:39:05.974+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T13:39:29.648+0000] {logging_mixin.py:137} INFO - Method: Z-score
[2023-01-04T13:39:29.651+0000] {logging_mixin.py:137} INFO - Count Of Outliers:  3298 from 151469
[2023-01-04T13:39:29.652+0000] {logging_mixin.py:137} INFO - Outliers Unique Values [ 4  5  6  7  8  9 10 11 12 29 34]
[2023-01-04T13:39:29.652+0000] {logging_mixin.py:137} INFO - Percentage Of Outliers:  2.177 %
[2023-01-04T13:39:29.660+0000] {logging_mixin.py:137} INFO - Method: IQR
[2023-01-04T13:39:29.663+0000] {logging_mixin.py:137} INFO - Count Of Outliers:  34597 from 151469
[2023-01-04T13:39:29.664+0000] {logging_mixin.py:137} INFO - Outliers Unique Values [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18 21 22 25 26 51 63 87]
[2023-01-04T13:39:29.665+0000] {logging_mixin.py:137} INFO - Percentage Of Outliers:  22.84 %
[2023-01-04T13:39:29.879+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Airflow.py", line 266, in data_transformation
    df_cleaned = clean(df).set_index("accident_index", inplace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 5451, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['accident_index'] are in the columns"
[2023-01-04T13:39:29.907+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_pipeline, task_id=MS1_Data_Cleaning_and_Transformation, execution_date=20230102T000000, start_date=20230104T133903, end_date=20230104T133929
[2023-01-04T13:39:29.926+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task MS1_Data_Cleaning_and_Transformation ("None of ['accident_index'] are in the columns"; 225)
[2023-01-04T13:39:29.995+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T13:39:30.034+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
