[2023-01-03T19:01:59.281+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:01:59.296+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:01:59.296+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:01:59.297+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2023-01-03T19:01:59.298+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:01:59.319+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 18:51:57.399301+00:00
[2023-01-03T19:01:59.324+0000] {standard_task_runner.py:55} INFO - Started process 1223 to run task
[2023-01-03T19:01:59.329+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T18:51:57.399301+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmpzhsjbpz7']
[2023-01-03T19:01:59.331+0000] {standard_task_runner.py:83} INFO - Job 44: Subtask dashboard
[2023-01-03T19:01:59.412+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [running]> on host 321b86f85270
[2023-01-03T19:01:59.511+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T18:51:57.399301+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T18:51:57.399301+00:00
[2023-01-03T19:01:59.512+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: dashboard() missing 1 required positional argument: 'filename'
[2023-01-03T19:01:59.523+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_pipeline, task_id=dashboard, execution_date=20230103T185157, start_date=20230103T190159, end_date=20230103T190159
[2023-01-03T19:01:59.541+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 44 for task dashboard (dashboard() missing 1 required positional argument: 'filename'; 1223)
[2023-01-03T19:01:59.580+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-03T19:01:59.615+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
