[2023-01-03T19:10:55.958+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:10:55.971+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:10:55.972+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:10:55.973+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-03T19:10:55.973+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:10:55.996+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 18:51:57.399301+00:00
[2023-01-03T19:10:56.002+0000] {standard_task_runner.py:55} INFO - Started process 2043 to run task
[2023-01-03T19:10:56.007+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T18:51:57.399301+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmpdenuwsyz']
[2023-01-03T19:10:56.010+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask dashboard
[2023-01-03T19:10:56.107+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [running]> on host 321b86f85270
[2023-01-03T19:10:56.239+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T18:51:57.399301+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T18:51:57.399301+00:00
[2023-01-03T19:11:00.509+0000] {logging_mixin.py:137} INFO - Dash is running on http://127.0.0.1:8050/
[2023-01-03T19:11:00.509+0000] {dash.py:1968} INFO - Dash is running on http://127.0.0.1:8050/

[2023-01-03T19:11:00.526+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-03T19:11:00.526+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-03T19:11:00.528+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
[2023-01-03T19:11:00.528+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-03T20:29:56.143+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-03T20:29:56.150+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2043. PIDs of all processes in the group: [2043]
[2023-01-03T20:29:56.152+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2043
[2023-01-03T20:29:56.161+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-03T20:29:56.212+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dashboard.py", line 76, in dashboard
    app.run_server(debug=False,host='0.0.0.0',port=8020)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-03T20:29:56.238+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=accidents_pipeline, task_id=dashboard, execution_date=20230103T185157, start_date=20230103T191055, end_date=20230103T202956
[2023-01-03T20:29:56.302+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task dashboard (Task received SIGTERM signal; 2043)
[2023-01-03T20:29:56.378+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2043, status='terminated', exitcode=1, started='19:10:55') (2043) terminated with exit code 1
[2023-01-03T20:29:56.380+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-03T20:29:56.415+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
