[2023-01-03T19:05:51.539+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:05:51.554+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [queued]>
[2023-01-03T19:05:51.555+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:05:51.556+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-01-03T19:05:51.557+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:05:51.580+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 18:51:57.399301+00:00
[2023-01-03T19:05:51.588+0000] {standard_task_runner.py:55} INFO - Started process 1557 to run task
[2023-01-03T19:05:51.594+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T18:51:57.399301+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmp2fhauwvq']
[2023-01-03T19:05:51.596+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask dashboard
[2023-01-03T19:05:51.695+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T18:51:57.399301+00:00 [running]> on host 321b86f85270
[2023-01-03T19:05:51.803+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T18:51:57.399301+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T18:51:57.399301+00:00
[2023-01-03T19:05:51.805+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: dashboard() missing 1 required positional argument: 'filename'
[2023-01-03T19:05:51.815+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_pipeline, task_id=dashboard, execution_date=20230103T185157, start_date=20230103T190551, end_date=20230103T190551
[2023-01-03T19:05:51.834+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task dashboard (dashboard() missing 1 required positional argument: 'filename'; 1557)
[2023-01-03T19:05:51.885+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-03T19:05:51.910+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
