[2023-01-03T19:51:38.944+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:46:51.588373+00:00 [queued]>
[2023-01-03T19:51:38.960+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:46:51.588373+00:00 [queued]>
[2023-01-03T19:51:38.961+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:51:38.962+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2023-01-03T19:51:38.963+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:51:38.983+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 19:46:51.588373+00:00
[2023-01-03T19:51:38.990+0000] {standard_task_runner.py:55} INFO - Started process 5769 to run task
[2023-01-03T19:51:38.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T19:46:51.588373+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmproskatxz']
[2023-01-03T19:51:38.996+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask dashboard
[2023-01-03T19:51:39.079+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:46:51.588373+00:00 [running]> on host 321b86f85270
[2023-01-03T19:51:39.181+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T19:46:51.588373+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T19:46:51.588373+00:00
[2023-01-03T19:51:43.353+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8010/
[2023-01-03T19:51:43.353+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8010/

[2023-01-03T19:51:43.362+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-03T19:51:43.363+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-03T19:51:43.364+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8010
 * Running on http://172.19.0.3:8010
[2023-01-03T19:51:43.364+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-03T19:56:17.296+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-01-03T19:56:17.300+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5769. PIDs of all processes in the group: [5769]
[2023-01-03T19:56:17.301+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5769
[2023-01-03T19:56:17.302+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-03T19:56:17.314+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dashboard.py", line 76, in dashboard
    app.run_server(debug=False,host='0.0.0.0',port=8001)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-03T19:56:17.327+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_pipeline, task_id=dashboard, execution_date=20230103T194651, start_date=20230103T195138, end_date=20230103T195617
[2023-01-03T19:56:17.347+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task dashboard (Task received SIGTERM signal; 5769)
[2023-01-03T19:56:17.395+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5769, status='terminated', exitcode=1, started='19:51:38') (5769) terminated with exit code 1
