[2023-01-03T19:07:16.735+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.MS2_final manual__2023-01-03T19:05:54.497116+00:00 [queued]>
[2023-01-03T19:07:16.748+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.MS2_final manual__2023-01-03T19:05:54.497116+00:00 [queued]>
[2023-01-03T19:07:16.749+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:07:16.750+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-03T19:07:16.750+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:07:16.771+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): MS2_final> on 2023-01-03 19:05:54.497116+00:00
[2023-01-03T19:07:16.778+0000] {standard_task_runner.py:55} INFO - Started process 1707 to run task
[2023-01-03T19:07:16.782+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'MS2_final', 'manual__2023-01-03T19:05:54.497116+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmpcmj5cf2z']
[2023-01-03T19:07:16.785+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask MS2_final
[2023-01-03T19:07:16.865+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.MS2_final manual__2023-01-03T19:05:54.497116+00:00 [running]> on host 321b86f85270
[2023-01-03T19:07:16.964+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=MS2_final
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T19:05:54.497116+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T19:05:54.497116+00:00
[2023-01-03T19:07:16.966+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: MS2() missing 1 required positional argument: 'filename1'
[2023-01-03T19:07:16.976+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_pipeline, task_id=MS2_final, execution_date=20230103T190554, start_date=20230103T190716, end_date=20230103T190716
[2023-01-03T19:07:16.991+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 51 for task MS2_final (MS2() missing 1 required positional argument: 'filename1'; 1707)
[2023-01-03T19:07:17.035+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-03T19:07:17.068+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
